using FiveEGoldBox.Application.Encounters;
using FiveEGoldBox.Application.Exploration;
using FiveEGoldBox.Application.Scenarios;
using FiveEGoldBox.Application.Scenarios.Definitions;
using FiveEGoldBox.Application.Travel;
using FiveEGoldBox.Core.Runtime;
using FiveEGoldBox.Core.Validation;

namespace FiveEGoldBox.Application.Tests;

/// The real Watchtower definition, as opposed to the hand-built one in
/// ScenarioDefinitionModelTests. This is content that has to hold up against
/// the running implementation it was derived from.
public sealed class WatchtowerScenarioDefinitionProviderTests
{
    [Fact]
    public void Definition_ValidatesWithoutErrors()
    {
        ValidationResult result = ScenarioDefinitionValidator.Validate(
            WatchtowerScenarioDefinitionProvider.Create());

        Assert.True(
            result.IsValid,
            "Watchtower content should carry no errors, but reported: "
                + string.Join(
                    "; ",
                    result.Issues
                        .Where(issue => issue.Severity == ValidationSeverity.Error)
                        .Select(issue => $"{issue.Code}: {issue.Message}")));
    }

    /// A real finding, kept visible rather than hidden by trimming the
    /// vocabulary: the save format records seven progress markers but nothing
    /// in the scenario ever produces SuccessReported or ScenarioCompleted.
    /// They are warnings, not errors, so the content still loads and plays.
    [Fact]
    public void Definition_ReportsItsTwoUnproducedProgressMarkers()
    {
        ValidationResult result = ScenarioDefinitionValidator.Validate(
            WatchtowerScenarioDefinitionProvider.Create());

        string[] unreachable = result.Issues
            .Where(issue => issue.Code == "scenario.progress.unreachable")
            .Select(issue => issue.Message)
            .ToArray();

        Assert.Equal(2, unreachable.Length);
        Assert.Contains(
            unreachable,
            message => message.Contains("SuccessReported", StringComparison.Ordinal));
        Assert.Contains(
            unreachable,
            message => message.Contains("ScenarioCompleted", StringComparison.Ordinal));
    }

    /// The map is generated by walking the implementation's own traversability,
    /// so the definition cannot drift from the tower the player actually walks.
    [Fact]
    public void Definition_MatchesTheImplementationsMap()
    {
        ExplorationMapDefinition map = Assert.IsType<ExplorationMapDefinition>(
            Assert.Single(
                WatchtowerScenarioDefinitionProvider.Create().Locations,
                location => location.LocationId
                    == WatchtowerRegionalRoute.WatchtowerLocationId)
            .ExplorationMap);

        Assert.Equal(WatchtowerExplorationMap.MapId, map.MapId);
        Assert.Equal(
            WatchtowerExplorationMap.StartingPosition,
            map.StartingPosition);

        foreach (ExplorationFloorDefinition floor in map.Floors)
        {
            for (int y = 0; y < map.Height; y++)
            {
                for (int x = 0; x < map.Width; x++)
                {
                    GridPosition position = new(x, y);

                    Assert.Equal(
                        WatchtowerExplorationMap.IsTraversable(
                            floor.Floor,
                            position),
                        floor.TraversablePositions.Contains(position));
                }
            }
        }

        // Both floors are linked, and the stair lands where the map says.
        StairDefinition stair = Assert.Single(
            Assert.Single(
                map.Floors,
                floor => floor.Floor == ExplorationFloor.GroundFloor)
            .Stairs);
        Assert.Equal(ExplorationFloor.UpperFloor, stair.DestinationFloor);
    }

    [Fact]
    public void Definition_MatchesTheImplementationsAmbush()
    {
        EncounterDefinition encounter = Assert.Single(
            WatchtowerScenarioDefinitionProvider.Create().Encounters);

        Assert.Equal(
            WatchtowerSignalEncounter.EncounterId,
            encounter.EncounterId);
        Assert.Equal(
            WatchtowerSignalEncounter.BattlefieldWidth,
            encounter.Width);
        Assert.Equal(
            WatchtowerSignalEncounter.BattlefieldHeight,
            encounter.Height);
        Assert.Equal(
            WatchtowerSignalEncounter.PartyStartingPositions,
            encounter.PartyStartingPositions);

        Assert.Equal(
            WatchtowerScenario.ToProgressId(
                WatchtowerScenarioProgress.RaidersDefeated),
            encounter.Outcome.VictoryProgressId);
        Assert.Equal(
            WatchtowerScenario.ToProgressId(
                WatchtowerScenarioProgress.PartyDefeated),
            encounter.Outcome.DefeatProgressId);
    }

    /// Accepting the commission is what opens the road; declining leaves the
    /// scenario exactly where it was.
    [Fact]
    public void Definition_ExpressesTheMissionDecision()
    {
        ScenarioDecisionDefinition decision = Assert.Single(
            WatchtowerScenarioDefinitionProvider.Create().Decisions);

        Assert.Equal(
            WatchtowerScenarioContent.OutpostLocationId,
            decision.LocationId);

        ScenarioDecisionOptionDefinition accept = Assert.Single(
            decision.Options,
            option => option.OptionId
                == Outposts.OutpostMissionChoice.AcceptMission.ToString());
        ScenarioDecisionOptionDefinition notYet = Assert.Single(
            decision.Options,
            option => option.OptionId
                == Outposts.OutpostMissionChoice.NotYet.ToString());

        Assert.Equal(
            WatchtowerScenario.ToProgressId(
                WatchtowerScenarioProgress.MissionAccepted),
            accept.ResultingProgressId);
        Assert.Null(notYet.ResultingProgressId);
    }
}
